apiVersion: apps/v1
kind: Deployment
metadata:
  name: wabapp-deployment
  labels:
    app: wabapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wabapp
  template:
    metadata:
      labels:
        app: wabapp
    spec:
      containers:
      - name: wabapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url     
---
apiVersion: v1
kind: Service
metadata:
  name: wabapp-service
spec:
  type: NodePort
  selector:
    app : wabapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 
      nodePort: 30100     
